create table if not exists public.waitlist (
  id bigint generated by default as identity primary key,
  email text not null unique check (email = lower(email)),
  source text not null default 'website',
  created_at timestamptz not null default now()
);

alter table public.waitlist enable row level security;

drop policy if exists "Public can join waitlist" on public.waitlist;
create policy "Public can join waitlist"
on public.waitlist
for insert
to anon
with check (
  length(email) between 5 and 254
  and source = 'website'
);

revoke all on table public.waitlist from anon;
grant insert on table public.waitlist to anon;
grant usage, select on sequence public.waitlist_id_seq to anon;

