import { Link } from 'react-router'

const privacySections = [
  ['What EchoTrace does', 'EchoTrace helps you organize information you provide about your own digital history, plus public sources you choose to save. It is not a people-search, surveillance, background-check, or private-investigation service.'],
  ['Information you provide and save', 'EchoTrace stores the account details needed to operate your workspace, your consent record, identifiers, timeline events, possible matches, notes, activity metadata, private archive files, and other records you choose to create. Private records are associated with your authenticated account.'],
  ['Google data EchoTrace accesses', 'Quick Gmail Scan requests only the restricted, read-only Gmail permission (https://www.googleapis.com/auth/gmail.readonly). During a scan, the browser searches for likely account-registration, verification, password, security, and account-notice messages. It temporarily processes message IDs, selected headers (including sender, subject, date, and mailing-list signals), and Gmail-provided snippets needed to identify account evidence. EchoTrace cannot send, modify, or delete Gmail messages and does not request attachments or full message bodies.'],
  ['How Gmail data is processed', 'Gmail API requests are made directly from your browser to Google. The short-lived OAuth access token remains in browser memory and is revoked after the scan. EchoTrace does not send the token, raw messages, Gmail addresses, message IDs, subjects, snippets, or mailbox files to its database or application server. Temporary scan details disappear when the scan page is cleared or closed.'],
  ['What can be saved from a Gmail scan', 'Nothing from a Gmail scan is saved until you review the results and choose Save selected for review. If you approve findings, EchoTrace stores only aggregate recovery records: a generic scan label, scan counts, service name, sender domain, evidence categories and counts, first and last observed dates, relevant-message count, confidence score and explanation, and your review status. Raw Gmail content and OAuth credentials are not included.'],
  ['How information is used', 'Information is used only to provide and secure your private digital-history recovery workspace, show evidence for your review, support exports and deletion, troubleshoot the service, and comply with applicable legal obligations. Google user data is not used for advertising, credit decisions, surveillance, selling data, or training general-purpose artificial-intelligence models.'],
  ['Sharing and service providers', 'EchoTrace does not sell or rent personal data. Google user data is not disclosed to other users or unrelated third parties. User-approved aggregate findings may be processed by infrastructure providers, including Supabase for authenticated database storage, only as necessary to operate EchoTrace and subject to access controls. Gmail scan traffic otherwise travels directly between your browser and Google.'],
  ['Google API Limited Use', "EchoTrace's use and transfer to any other app of information received from Google APIs will adhere to the Google API Services User Data Policy, including the Limited Use requirements."],
  ['Retention and deletion', 'User-approved records remain until you delete them or delete your EchoTrace application data or account. You can delete an individual Gmail scan summary and its findings from Find My Accounts, delete individual records and files, delete all application data, or request permanent account deletion. Deleting a scan summary does not delete a timeline event you previously chose to create from it; you can delete that timeline event separately.'],
  ['Security and access', 'EchoTrace uses HTTPS, authenticated access, user-owner Row Level Security for private database records, and private storage paths scoped to the authenticated user. No database service-role key is included in browser code. No method of storage or transmission is guaranteed to be completely secure.'],
  ['Your control', 'You decide whether to connect Gmail, which findings to save, and whether to accept, reject, or mark findings uncertain. You can revoke EchoTrace access from your Google Account permissions, export your EchoTrace records as JSON or CSV, correct saved records, and use the deletion controls described above.'],
  ['Limits', 'Public sources may be incomplete, outdated, or wrong. A confidence score is an explainable estimate—not proof that a result belongs to you. You make the final decision.'],
  ['Contact', 'Questions or requests about this notice or your data can be sent to mporter84@email.com.'],
]
const termsSections = [
  ['Permitted use', 'You may use EchoTrace only to reconstruct digital history that belongs to you. You must have the right to upload each private file and save each identifier.'],
  ['Email-history analysis', 'You may analyze only a mailbox you control as part of reconstructing your own digital history. Quick Gmail Scan uses temporary read-only permission and disconnects after the scan. Supported .mbox files remain a local advanced option. EchoTrace saves only the aggregate findings you select.'],
  ['Prohibited use', 'Do not use EchoTrace for surveillance, harassment, stalking, doxxing, employment or tenant screening, background checks, private investigation, arbitrary people-search, or research about another person without their informed authorization.'],
  ['Public-source rules', 'Do not bypass authentication, paywalls, CAPTCHAs, robots.txt, access controls, or platform restrictions. Follow website terms and applicable law. Guided searches are user-directed outbound links, not automated scraping.'],
  ['Result accuracy', 'EchoTrace does not guarantee that a public result belongs to you. Keep original sources, review conflicts, correct mistakes, and treat confidence as an estimate.'],
  ['Account responsibility', 'Keep your credentials secure. Do not upload malware, unlawful content, secrets belonging to others, or files you do not have permission to store.'],
  ['Availability', 'This MVP may change and may experience interruptions. Export important records regularly.'],
]

function LegalPage({ title, intro, sections }: { title: string; intro: string; sections: string[][] }) {
  return <main className="min-h-screen bg-bone px-5 py-10 text-ink"><div className="mx-auto max-w-3xl"><div className="flex items-center justify-between"><Link to="/" className="text-2xl font-semibold">EchoTrace</Link><Link to="/login" className="text-body-s underline decoration-gold underline-offset-4">Sign in</Link></div><p className="mt-16 text-label uppercase text-gold">Legal</p><h1 className="mt-3 text-5xl font-semibold tracking-tight md:text-7xl">{title}</h1><p className="mt-6 text-body-l text-ink/60">{intro}</p><div className="mt-12 space-y-10">{sections.map(([heading, body]) => <section key={heading}><h2 className="text-2xl font-semibold">{heading}</h2><p className="mt-3 text-body-m leading-relaxed text-ink/65">{body}</p></section>)}</div><p className="mt-14 border-t border-ink/10 pt-6 text-micro uppercase text-ink/40">Last updated August 9, 2026</p></div></main>
}

export function PrivacyPage() { return <LegalPage title="Privacy Notice" intro="Your digital history can be deeply personal. EchoTrace is designed around ownership, source attribution, local processing, correction, portability, and deletion." sections={privacySections} /> }
export function TermsPage() { return <LegalPage title="Terms of Use" intro="EchoTrace is a self-recovery tool. Using it means respecting other people’s privacy, public-source rules, and the boundaries below." sections={termsSections} /> }
