import { Link } from 'react-router'

type Section = [string, string]

const privacySections: Section[] = [
  ['What EchoTrace does', 'EchoTrace is a privacy-first self-recovery workspace for organizing information you provide about your own digital history and public sources you choose to save. It is not a people-search, surveillance, background-check, stalking, doxxing, or private-investigation service.'],
  ['Information we collect', 'Depending on how you use the service, EchoTrace may process your account name and email address, historical identifiers you choose to add, timeline events, notes, source URLs, possible-match records, consent records, activity and security metadata, uploaded archive files, import metadata, billing entitlement records, and information you voluntarily provide to customer support.'],
  ['Email-history and saved-login imports', 'When you select an email .mbox export or saved-login .csv export, EchoTrace analyzes the file locally in your browser. Raw mailbox contents, message bodies, sender addresses, subject lines, and password or secret values are not uploaded as part of the import workflow. Only findings you explicitly choose to save are transmitted, and saved findings are aggregate recovery records rather than raw credentials or message contents. You are responsible for using exports you are authorized to possess.'],
  ['Public-source research', 'Guided public searches are user-directed outbound searches. When you click one, the selected identifier or search terms are sent to the destination provider and become subject to that provider’s privacy policy and terms. EchoTrace does not represent that a third-party source is accurate, current, complete, or affiliated with you.'],
  ['How information is used', 'We use information to provide, secure, maintain, troubleshoot, improve, and support EchoTrace; process purchases and subscriptions; prevent abuse; respond to lawful requests; maintain records of consent; and comply with applicable law. EchoTrace does not sell or rent personal data and does not use your private recovery records to train general-purpose artificial-intelligence models.'],
  ['Service providers', 'EchoTrace relies on service providers needed to operate the product, including Supabase for authentication, database and private storage infrastructure, Vercel for application hosting, and Stripe for payment processing and billing management. These providers may process information as necessary to provide their services. Payment-card details are handled by the payment processor rather than stored in EchoTrace application tables.'],
  ['Billing information', 'For paid plans, EchoTrace stores billing entitlement and subscription status information needed to provide purchased features. Stripe processes payment information and provides EchoTrace with billing identifiers and status information. Cancellation and payment management are available through the billing portal when applicable.'],
  ['Cookies, local storage, and similar technologies', 'EchoTrace uses browser storage where necessary for application functions such as authentication state, waitlist convenience, pending plan selection, and local import processing. The current application does not intentionally use advertising cookies or sell information for targeted advertising. If analytics, advertising, or additional tracking technologies are introduced, this notice will be updated before those technologies are used in a way that requires additional notice or consent.'],
  ['Data retention', 'We retain account and application records while your account is active or as needed to provide the service. You control records you create and can delete individual records or application data from the product. Certain records may need to be retained when required by law, to resolve disputes, prevent fraud or abuse, enforce agreements, or protect security. When information is no longer required for these purposes, it is deleted or de-identified according to our operational processes.'],
  ['Your choices and privacy rights', 'Depending on where you live, you may have rights concerning access, correction, deletion, portability, restriction or objection to certain processing, and other rights provided by applicable law. EchoTrace provides in-product correction, export, and deletion controls where available. You can also contact us at mporter84@email.com to request access, correction, deletion, or clarification. We may need to verify your identity before fulfilling a request.'],
  ['Children', 'EchoTrace is not directed to children under 13. Do not create an account or submit personal information if you are under the minimum age permitted by applicable law. If we learn that personal information was collected from a child in violation of applicable law, we will take appropriate steps to delete it.'],
  ['Security', 'EchoTrace uses authenticated access, HTTPS, owner-scoped Row Level Security, private storage paths, signed file downloads, and server-side handling of privileged service credentials. No method of storage or transmission can be guaranteed completely secure. You are responsible for protecting your account credentials and for using trusted devices when processing private exports.'],
  ['Deletion', 'You can delete individual records, private files, all application data, or your account. Account deletion is designed to remove the Supabase Auth account and associated application data after archive cleanup succeeds. Deleting an import summary does not automatically remove a timeline event you previously created from that evidence; those records can be deleted separately.'],
  ['Data incidents', 'If a security incident involving personal information occurs, EchoTrace will take reasonable steps to investigate, contain, remediate, and provide notices required by applicable law.'],
  ['International users', 'EchoTrace is operated from the United States. If you access the service from another country, your information may be processed in the United States and other locations used by our service providers. Additional rights or transfer requirements may apply depending on your location.'],
  ['Changes to this notice', 'We may update this notice as the service changes or legal requirements evolve. Material changes will be reflected by updating the effective date and, where appropriate, providing additional notice.'],
  ['Contact', 'Privacy questions and requests can be sent to mporter84@email.com. EchoTrace is operated by Matthew Porter as a sole proprietor from Pennsylvania, United States. This notice is an operational privacy notice and should be reviewed by qualified counsel for the jurisdictions in which EchoTrace is offered.'],
]

const termsSections: Section[] = [
  ['Acceptance', 'By creating an EchoTrace account or using the service, you agree to these Terms of Use and the Privacy Notice. If you do not agree, do not use EchoTrace.'],
  ['Who may use EchoTrace', 'You must be legally able to enter a binding agreement and meet the minimum age required by applicable law. EchoTrace is not directed to children under 13.'],
  ['Self-recovery only', 'EchoTrace is designed to help you reconstruct your own digital history. You may use the service only for information and accounts you own or are authorized to manage. You must have the right to upload each file and submit each identifier.'],
  ['Prohibited uses', 'You may not use EchoTrace for surveillance, stalking, harassment, doxxing, employment or tenant screening, background checks, credit decisions, private investigation, arbitrary people-search, credential discovery, unauthorized account research, or investigation of another person without appropriate authorization. You may not use the service to facilitate unlawful activity or harm.'],
  ['Public-source rules', 'Do not bypass authentication, paywalls, CAPTCHAs, robots.txt, access controls, rate limits, or platform restrictions. Do not scrape sources when automated access is prohibited. Follow the terms and policies of third-party sites. Guided searches are outbound links selected by you, not authorization to automate access.'],
  ['Your content and responsibility', 'You retain your rights in information and files you submit. You represent that you have the rights and permissions necessary to submit them. Do not upload malware, unlawful material, secrets belonging to another person, or content you are prohibited from storing. You grant EchoTrace only the limited rights needed to provide the service, store your records, process selected findings, secure the platform, and comply with law.'],
  ['Accuracy and confidence', 'EchoTrace results are not identity proof. Public sources can be incomplete, outdated, duplicated, or wrong. Confidence scores are estimates based on documented signals. You are responsible for reviewing sources and making the final decision about whether a result belongs in your history.'],
  ['Free service', 'The free plan provides the features and limits displayed on the pricing page at the time you use it. Features and limits may change prospectively.'],
  ['Recovery purchase', 'Recovery is a one-time purchase at the price displayed at checkout. A successful purchase unlocks the Recovery features described at checkout for the account associated with the purchase, subject to these Terms and applicable law.'],
  ['Vault subscription', 'Vault is a recurring monthly subscription at the price displayed at checkout, unless a different price is expressly shown. It renews automatically until canceled. You may cancel through the billing portal when available. Cancellation stops future renewal; unless otherwise required by law or expressly stated at checkout, access continues through the paid period and partial-period refunds are not provided.'],
  ['Refunds', 'For Recovery one-time purchases, you may request a refund within 14 days of purchase provided you have not used any paid Recovery feature. Vault subscription payments are generally non-refundable for a period already billed, except where required by law or where EchoTrace elects otherwise. Contact mporter84@email.com with your account email and purchase details. Nothing in this section limits mandatory consumer refund rights.'],
  ['Taxes and payment processing', 'Prices may exclude taxes unless the checkout display states otherwise. Stripe or another designated payment processor handles payment-card processing. You authorize the applicable processor to charge the selected payment method for purchases and recurring subscriptions.'],
  ['Cancellation and account deletion', 'Canceling a subscription does not automatically delete your account or data. You may delete application data or your account through Settings. Account deletion may end access to paid features and does not necessarily create a refund for charges already incurred.'],
  ['Suspension and termination', 'We may suspend or terminate access when reasonably necessary for security, abuse prevention, violation of these Terms, legal compliance, fraud prevention, or protection of the service or other users. Where practical, we will provide notice and an opportunity to resolve the issue.'],
  ['Availability and changes', 'EchoTrace is provided as an evolving service. Features, limits, pricing, and availability may change. We will not retroactively change the price of a completed purchase. We may discontinue a feature or service with reasonable notice where practicable.'],
  ['Intellectual property', 'EchoTrace software, branding, design, documentation, and original content are owned by EchoTrace or its licensors and are protected by applicable intellectual-property laws. These Terms do not transfer ownership to you.'],
  ['Third-party services and links', 'EchoTrace may link to or interact with third-party websites and services. Their availability, content, privacy practices, and terms are controlled by those third parties. EchoTrace is not responsible for third-party services.'],
  ['Disclaimers', 'To the extent permitted by law, EchoTrace is provided on an as-is and as-available basis. We do not warrant uninterrupted availability, complete recovery of your history, accuracy of third-party sources, or that every possible match will be found.'],
  ['Limitation of liability', 'To the maximum extent permitted by applicable law, EchoTrace and its operators will not be liable for indirect, incidental, special, consequential, exemplary, or punitive damages arising from use of the service. To the maximum extent permitted by law, aggregate direct liability for claims relating to the service will not exceed the greater of the amount you paid EchoTrace for the service during the twelve months before the event giving rise to the claim or $100. Nothing in these Terms excludes liability that cannot legally be excluded.'],
  ['Indemnification', 'To the extent permitted by law, you agree to defend and hold harmless EchoTrace and its operators from claims arising from your unlawful use of the service, your violation of these Terms, or your submission of content you did not have the right to submit.'],
  ['Order of documents', 'If there is a conflict about a purchase, the specific checkout disclosure shown before payment controls for that transaction, followed by the Refund & Cancellation Policy, these Terms, and the Privacy Notice for their respective subjects. Nothing in these documents limits rights that cannot legally be waived.'],
  ['Governing law and disputes', 'EchoTrace is operated by Matthew Porter, as a sole proprietor, from Pennsylvania, United States. These Terms are governed by the laws of the Commonwealth of Pennsylvania, without regard to conflict-of-law rules. Subject to any rights that cannot legally be waived or requirements that apply to a particular consumer dispute, disputes arising from these Terms or the service will be brought in the state or federal courts located in Pennsylvania, and you consent to their jurisdiction and venue. Nothing in this section limits rights that cannot legally be waived.'],
  ['Changes to these Terms', 'We may update these Terms as the service changes or legal requirements evolve. Material changes will be reflected by updating the effective date and, where appropriate, providing additional notice. Continued use after an effective update constitutes acceptance only to the extent permitted by applicable law.'],
  ['Contact', 'Questions about these Terms, purchases, cancellations, or refunds can be sent to mporter84@email.com. EchoTrace is operated by Matthew Porter as a sole proprietor from Pennsylvania, United States.'],
]

function LegalPage({ title, intro, sections, notice }: { title: string; intro: string; sections: Section[]; notice?: string }) {
  return <main className="min-h-screen bg-midnight px-5 py-10 text-slate-300"><div className="mx-auto max-w-3xl"><div className="flex items-center justify-between"><Link to="/" className="text-2xl font-semibold text-white">EchoTrace</Link><Link to="/login" className="text-body-s text-cyan-300 underline underline-offset-4 hover:text-cyan-200">Sign in</Link></div><p className="mt-16 text-label uppercase tracking-[0.16em] text-cyan-300">Legal</p><h1 className="mt-3 text-4xl font-semibold tracking-tight text-white md:text-6xl">{title}</h1><p className="mt-6 text-body-l text-slate-400">{intro}</p>{notice && <div className="mt-8 border border-amber-400/30 bg-amber-400/5 p-5 text-body-s leading-relaxed text-amber-100">{notice}</div>}<div className="mt-12 space-y-10">{sections.map(([heading, body]) => <section key={heading}><h2 className="text-2xl font-semibold text-white">{heading}</h2><p className="mt-3 text-body-m leading-relaxed text-slate-400">{body}</p></section>)}</div><div className="mt-14 border-t border-night-border pt-6 text-micro uppercase text-slate-500"><p>Last updated October 3, 2026</p><p className="mt-2 normal-case tracking-normal">EchoTrace is operated by Matthew Porter as a sole proprietor from Pennsylvania, United States. These documents describe the current product, have not yet been reviewed by an attorney, and are not a substitute for advice from qualified counsel.</p></div></div></main>
}

export function PrivacyPage() { return <LegalPage title="Privacy Notice" intro="Your digital history can be deeply personal. EchoTrace is designed around ownership, source attribution, local processing, correction, portability, and deletion." notice="Draft — pending legal review. This notice describes the current EchoTrace MVP and has not yet been reviewed by an attorney; it is not legal advice and may change before commercial launch. Please contact us if you need a privacy request handled directly." sections={privacySections} /> }
export function TermsPage() { return <LegalPage title="Terms of Use" intro="EchoTrace is a self-recovery tool. Using it means respecting other people’s privacy, public-source rules, payment terms, and the boundaries below." notice="Draft — pending legal review. The commercial provisions below cover the current Free, Recovery, and Vault plans and have not yet been reviewed by an attorney; they are not legal advice and may change before commercial launch. EchoTrace is operated by Matthew Porter as a sole proprietor. The governing law and dispute provisions are stated below." sections={termsSections} /> }
